export const actionTypes = {
  GET_EVENTS: 'GET_EVENTS',
  NEW_EVENT_REQUEST: 'NEW_EVENT_REQUEST',
  NEW_EVENT_SUCCESS: 'NEW_EVENT_SUCCESS',
  CREATE_EVENT_FAIL: 'CREATE_EVENT_FAIL',
  CLEAR_INPUT_ERROR: 'CLEAR_INPUT_ERROR',
  CONNECTION_ERROR: 'CONNECTION_ERROR'
};
